### ISSUE TITLE
problem in getting images from some manga!

### ISSUE THREAD

**Issue by grvn-ht** [eliottness/episcan#1]
hey @eliottness !!

I also wanted to scrap japscan using python, https://github.com/grvn-ht/JapScrap/blob/master/JapScrap.
My script is not as well organised as yours and comments are in french but you might understand what i did.
Like you I wanted to extract all the url informations that links to the images and then increment on the number of pages of a chapter to directly request them from the server.
But recently they started hosting their manga on this server: https://c.japscan.co/ with random url to get the images.
And now I don't understand how to easily get them anymore.

Try scrapping https://www.japscan.co/lecture-en-ligne/le-sommet-des-dieux/volume-1/ and you will see.

If you have any hint on how you would handle the problem I would be glad to hear it!

Have a good day!

**Comment by eliottness** [comment]
Hi @grvn-ht 

Firstly I want to specify that this project purpose is to be a fully automated website which scrap mangas daily to read them on clean, no-ads pages. Now this project is still in dev phase and the core scrapers have yet to be implemented.

But this does not mean that I do not have your solution. As Japscan encrypt their images with a weird version of base64, the easiest way to get them is to navigates pages like a human would do and to screenshot the image element. like this:
```
elem = driver.get_element_by_xpath(your_xpath_img_tag)
elem.screenshot(path_to_store_img)
```

One of my old script was already using it [here](https://github.com/eliottness/japscan-scrapper/blob/master/japscan2png.py).
But I also saw that you were using python2 in your script while mine is using python3, you can find more informations about the screenshot function of selenium [here](https://stackoverflow.com/questions/15018372/how-to-take-partial-screenshot-with-selenium-webdriver-in-python).

Hope I helped you with this, you can ask more if you feel that way.

Have a good day.

**Comment by grvn-ht** [comment]
Thanks for the answer!
For sure I will follow your project!
